name: Publish release APK

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package-release-apk:
    name: Generate release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Generate signed APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign APK with keystore
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ MIIJwAIBAzCCCWoGCSqGSIb3DQEHAaCCCVsEgglXMIIJUzCCBaoGCSqGSIb3DQEHAaCCBZsEggWXMIIFkzCCBY8GCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFKoviSXjO+D1aV5934dYWj5pfT4kAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQcgao/TQOa+/2J2iHWAfkhgSCBNBqLDJPmaWR4RQ7fDGnqMohV2fpLBVxdo2cY6jMf2hoHjXSsFswdAraMqvaAW5UFzJFGQDON0h2wI5PHO2qnmwV0h6n9SpGKbi/27pRIlW4tb0annKc60bZuZuFps0mMkfirsbEcz1Bl6HgfsUftS7onQxrDdxhYvbXfGir20qh8zdcbfOxrfScDgKLVWC4kzLKh1Us8TU2J34ulM6hUFBw0bB3aIHAGBtcZg7S9DlkjYowp1dr+P3ozCSJO+aXZepmE4eE2eLDIj1rK1FuC9ZsFpYPhT+q8N1fkYIC+mK+BpeoCvM7RvPStBJm4506whCdyoURaUBANG0SV1ZaN0KvAcnlRjh0LA2jTKZkdsX1x5VbFSAOYSSbnl7hWM/53d45OhpVwpF2drShUncIiPP4uA4jfeoGrK3WRlbiseV1VPB7DzUwWrbHCayBAQGzs0ypIi1Ohl/6uLk97E3soknUmMqAOrWW2G2BX/2KNQFP+uJvZHzNfPoyVNjy+txy7rTuu11tE2QT9Jj1csW1m+W6mTPsioXp502wZOUmlrbCGrmy9s9KD9kk4zDcgg9JfScFidLvWNekS+fnrmWaLg1ABnJ01wNv/7B2V2oR2J66M79CWMcQslBAZV3YvAIKhqVr8UWdDUzf5Voo/Dn4Sipu/FoVSYAFfOP8cDirHoBlBoV6725UUh3EzZgmwZHkbxXsuW5taHOyUs+YzP1p9maqDHtP6FmcrpdOsBqn2o6wZatntT6muJJTrXsV3ZTPA0PfkYYqmIFxSQjMgfWj9tDJirplpZuYMXznjJDijCgVIbFOZLUnop1tzxHrCac1PkR7XaUs8tsqS8X+hqoD8e81ZGgm/nPM2VqTs9EBsORT2V39iKGlp5+qKG7B2cwFRuaTc5MN7GPnZtmG5/ctlDcOf/pOoq2qQLKH3aaMUVlwFb4PuaC1x3j403wlQp0LYP2IwKfAkoOVkcgcB2VXPxNDKJ8Gqj+hl2m3z/tn8fIcz29PT2HQ4jbQIpXtkJBS7+MR235VXPIBGbd984ry7M74O6ikxhAv/0S10NX/7SOoz6HHgx/t9ZNpHq/6/t/92l2DVBcFsYrX+6ElfycIDDEUHaS9qQqcvlA1XW8p5O48VxHazSfblREFhi3zQKqpoU5vp1jE6/nz5Dk21QCtfHFw9kf6eCnaZ+RlTKv/iiofRvF16H/aRjIm/GS89/yJGmCHGiJKyr0oeZOGY0gi3P4k5O15KVLr0DR/i8qjAqkVBWJs1jhyrFJ+V8IChjFytsu7ybRSZ2kumlPw4Ok/dgQAIT9oWyyOLAUlJqIwLS4yWJKNY6sqpKqIQ7gv89d4M/m5nyLeL7m+JqhI6ETWZCCm2znakItn3MpOV/Ws7XaXSHp6OBxAHaqxbP0BG8MKC7uqs02KPwIHu1IDTbjosxhlS7HbNZyGObYxUmpA5b6PFVw9fwQ5e0febFkwWfWSinkZ9DOD1SFWAXMn3oChl2tz7SdkAyLF9AHpYFikJ52vpVFpRI5IirlppwjqoVWnsTPoh/4QtRKJag5ETEquJhb8i9EHmatbk9W7W7cGmXuY9CztR4cNw3rjn46WfO0/uqFzOhhZ1G+Slwhydl3J8Snf+m8/flgXKBRTU8rgXG8YqDE8MBcGCSqGSIb3DQEJFDEKHggAawBlAHkAMDAhBgkqhkiG9w0BCRUxFAQSVGltZSAxNzI1MzY2MDU4MTQ4MIIDoQYJKoZIhvcNAQcGoIIDkjCCA44CAQAwggOHBgkqhkiG9w0BBwEwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFPO3PDu5WHUqE6zUQKDjeJCe5V83AgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQbABTiZOMPaUud/q5bsEwUYCCAxDpNePCNhI1H5t1qgs0H6d0uiVfJ7OPzTDLB58X9EcH7gFiabpwJyQJXS4qrOJd+uZP4IKR5AouMmbATOucBvmUETPCMuVtBwVxe1ajrn2aYzdHEmilTN/wBppDSQaBA4RMY7DY+DuQIpmwDkbu5FkV5JQqW2ffUQO5wmCJZZ3FFqZfMETZvMgxN+XWoZBSvNFBfX70aEGArXwq//6yzIZnrWkvEpoM2DFMe7YkyNjM5nCqHsBuo/RFyvvkEh11cj40uUNbBMuIy74L/kYPQvB4CsSO6WI9sDO0oW8N7gttVXxefzv8A68nolZb5FNLzqKc8+4zYoWM3xwhJUZcKW8vc6WssqS8bwUyrHNlIdxlp5u65nUrM4FJc1AiVNOX8qW1AKbWNhTN9jAKKShPy2oxzl855Fs8lp2jhCxjlsPQ82bTwUcCC37bwzt4kq0w0ZBZna/tJGNL1BhsLZ6y7dz12eyI6t4RWKPfozTqr8cVohdsXxzxxinYWdYhjtsn8UkdDTiI6S/M8S3nxMMRz3EHeN02owAwP7Xyw1+Z1ILagU/CvKqIY0wVrMxiyN5W+7HqG2nADS6jZhDAXZuyDMWlxzWafGRTPXrm3YV0nTxDXHorUzjxza85Th0Rche9H5DPqgnvmLMvWA6RUL5JPoVl13rOxJVayeLv8F7CpE/4tE9lscUCOD/+PN0MBs+TdtyGH+WNUOZ6/zSmgMx5IZiwvCzTHmx/ZUtf4VULtbEYNelc+3QVW2sva+JFT4txTg+5wwYYyHmkX1eSC5UISQ+5svVsCbiYATA0xJsaQ1CNezaidcjlfETjTomVtIz/vxvwxgIJKiL2f3Il2wluHhq8B1xvFMyOpBR6ZhfTxG4q84TkfxGdyxQQM4UPxwT3YPGtvURJ2YeYrzZYNdnW/rtq/PCf54r0ngeQ8yNnXaj/ONvEzkGqlIV6NyGTaR9HNrHFtdPo6wZGhCSt0wyqFUxs1TQxgEz9AlO+FUzY5zWktj99Xx27m1MW06eFHpeize5sovDV+Dve1Cy9uJ24pFBmME0wMTANBglghkgBZQMEAgEFAAQga8pIsMAzKvag+dLevB/tDFoKfXUKsg5lT5JLpf/TE00EFMKRDp4/5QHiaKpeV8pIMgaOQ8pEAgInEA== }}
          alias: ${{ key0 }}
          keyStorePassword: ${{ w2x5p801 }}
          keyPassword: ${{ w2x5p801 }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload release APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Echo APK
        run: echo Signed APK FILE ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Release signed APK
        uses: MicahSphelele/action-publish-signed-apk@main
        env:
          GITHUB_TOKEN: ${{ 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 }}
          APP_FOLDER: app
          FILE_DIR: ${{steps.sign_app.outputs.signedReleaseFile}}
